### ISSUE TITLE
Major buttons vs parameter tabs

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/napari-LF#19]
Swap the location of the block containing the buttons with the parameters block. It could make the order of operations more intuitive.

**Comment by amitabhverma** [comment]
Do you mean like this @gschlafly ?

![image](https://user-images.githubusercontent.com/2894099/208163091-9eed91c5-c4f2-4a1a-bd4b-ac41692d911c.png)

**Comment by gschlafly** [comment]
Exactly!
