### ISSUE TITLE
Error warning when opening napari

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/napari-LF#20]
When opening napari, I get the following error message even after a new installation. Some information seems to be saving in to the environment. I am going to try opening napari into a new virtual environment.

![image](https://user-images.githubusercontent.com/23206511/212385100-4a6bdb06-9e03-4ca6-971d-00128b2de829.png)

**Comment by gschlafly** [comment]
Note: These attempts are made on a Windows OS.

I created a new conda environment. I used the following command to install napari along with the napari-LF plugin.
> pip install git+https://github.com/PolarizedLightFieldMicroscopy/napari-LF.git@NeuralNets_integration2

napari successfully opens with only the warning message of 
![image](https://user-images.githubusercontent.com/23206511/212389671-1597b9a9-0b77-4a13-88b7-f6d238915448.png)
However, the napari-LF plugin fails to open when selected from the dropdown menu. Below is the output in the napari debugger.
<img width="652" alt="2023-01-13 napari debugger ulens_pitch" src="https://user-images.githubusercontent.com/23206511/212389985-469507cb-6a1b-4bf4-bab8-c84d344cc1fc.png">

Potential cause: Another package might need to be included in the setup.cfg file

**Comment by amitabhverma** [comment]
I'm a little confused with this issue. If this was a new napari installation, didn't it install the latest QT lib which should be >=5.12.3 and not 5.9.7 ? Does updating the QT lib to the recommended version change any messages ?

**Comment by amitabhverma** [comment]
BTW, the last error message probably is numpy related. I had to downgrade numpy to 1.21 since the latest was giving issues.

**Comment by amitabhverma** [comment]
Tried a clean conda installation and was still getting our plugin disabled at startup and no way to enable it. Finally, the following did the trick:

In napari console:
```
from napari.settings import SETTINGS
SETTINGS.reset()
```
Restart napari

PS: still need to downgrade numpy==1.23.5 (https://github.com/PolarizedLightFieldMicroscopy/LFAnalyze-fundamentals/issues/3)

**Comment by gschlafly** [comment]
Numpy issues have (most likely) been resolved. The non-Neural Net files in the lfa folder can be replaced by those in the [numpy branch](https://github.com/PolarizedLightFieldMicroscopy/LFAnalyze-fundamentals/tree/numpy).
