### ISSUE TITLE
Create space so the important variable fields are emphasized

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/napari-LF#22]
#### How enhancement relates to a problem
When napari window size is smaller than a typical computer display, vertical height of the parameters region is limited. This makes it difficult to see multiple of the parameters simultaneously.

#### Preferred solution
- [x] Make the napari-LF logo a at the top slightly smaller.
- [x] Remove the metadata field.
- [x] Shrink the vertical height of the *Calibrate*, *Rectify*, *Deconvolve*, and *Stop*, buttons.
- [x] Shift the relative horizontal location of the green checkmark and the *Calibrate*, *Rectify*, and *Deconvolve* buttons such that it is clear which process is completed when the green checkmark appears.

#### Alternative solutions considered
- [x] Turn the _Presets_ and _Comments_ fields into a dropdown area.

#### Additional context
The header could look more similar to that of the plugin [brainglobe](https://docs.brainglobe.info/cellfinder-napari/introduction). A link to the corresponding website, documentation, and source code are included.

**Comment by gschlafly** [comment]
Is it possible to make the _Deconvolve_ button disabled if there is not a _*.lfc_ file in the directory? I think that would make it clear to the user that the calibration step is required for the deconvolution step.

**Comment by amitabhverma** [comment]
> Is it possible to make the _Deconvolve_ button disabled if there is not a _*.lfc_ file in the directory? I think that would make it clear to the user that the calibration step is required for the deconvolution step. @amitabhverma

Implemented in the latest /NN branch 
https://github.com/PolarizedLightFieldMicroscopy/napari-LF/blob/4bfc52b08297b26fd1454723fe3577832947a085/src/napari_lf/_widgetLF_gui.py#L1521-L1529
