### ISSUE TITLE
New page for Neural Net processes

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/napari-LF#24]
#### How enhancement relates to a problem
Having the Neural Net (LFMNet) content and the LF Analyze content viewable simultaneously adds clutter to the screen.

#### Preferred solution
Extract the Neural Net (LFMNet) content onto its own "page".
- [x] Add two buttons under the _Comments_ field: _LF Analyze_ and _Neural Net_.
- [x] When _LF Analyze_ is selected by the user, all the current parameter options are displayed, except for the LFMNet tab. The bottom processing buttons also remain.
- [ ] When _Neural Net_ is selected, only fields related to the neural net deconvolution process should be displayed. Keep only the bottom _Deconvolve_ and _Stop_ buttons, with their actions changed accordingly.

Neural Net content (listed in order to appear)
1. some words related to the training process and a relevant link containing more information
2. _Light field image_: field to select the raw/rectified light field image
3. _Model_: field to select training model file
4. _Output image stack_: field to type in the filename desired for the output image
5. _Network model inspector_:  field area that displays content inside the model file selected

#### Alternative solutions considered
The Neural Net page could be its own "subwidget" instead of "page" within the same widget display.

#### Additional context
The rectification process is being included in the process that occurs when the model is applied to the image (#21).

**Comment by gschlafly** [comment]
I still think would be helpful to make the _LF Analyze_ and _Neural Net_ zones separate widgets within our napari-LF plugin. This is the napari built-in method for doing what we are trying to achieve. It is similar to the one button toggle that @rudolfoldenbourg suggested, because it leaves room for additional methods to be added to napari-LF. Below is a screen recording showing two of these widgets within a single plugin ([napari-pyclesperanto-assistant](https://www.napari-hub.org/plugins/napari-pyclesperanto-assistant)) being open and moved around. Widgets can also be moved outside the napari viewer to a different place on your display screen.

https://user-images.githubusercontent.com/23206511/215179079-20b1ce76-17c7-448c-a8c4-3237bd13aaec.mp4

**Comment by rudolfoldenbourg** [comment]
Thanks, Geneva, for illustrating this option. As an alternative, here are two mockups that show how a single button might work a) to switch between two processing modes and b) give a heading to the panels below the button. What is above the button, applies to both modes, what is below is specific to each mode:
![WidgetLayoutLFA](https://user-images.githubusercontent.com/2894530/215197678-c45851a6-7deb-4a4c-a70e-b9e4910bc4a0.jpg)
![WidgetLayoutNN](https://user-images.githubusercontent.com/2894530/215199638-48fb14ff-007f-4b7c-b2f7-5ca13f66c3bd.jpg)

In the Neural Net panel, the first tab Files can be used to setup the deconvolution, the second tab Training can include some narrative about training an NN using a Jupyter notebook, which will be available in the lfa directory of the distribution. A button in that tab might switch to the Jupyter notebook in question (e.g. main_train_neural_net.ipynb).

**Comment by gschlafly** [comment]
I like it! @rudolfoldenbourg

**Comment by amitabhverma** [comment]
@rudolfoldenbourg @gschlafly 
I'd like to suggest if we are thinking more in line of _cycling_ through the choices does something like below make more sense.. this would make the task of setting the image easy since it does not need to be an image with button _feel_.

![image](https://user-images.githubusercontent.com/2894099/215359951-541844cc-c741-49fc-bcda-bae9bcf32108.png) 

@gschlafly wrt your suggestion of independent widgets, I don't believe the one in the example share any sort of settings between them, like setting the data directory, etc. So in our case we'd have the divide into 3 widget sections.
- Data dir. tab, Misc, Hardware, About (currently merging these together is the plan irrespective of which layout we decide)
- LF Analyze
- Neural Net

**Comment by gschlafly** [comment]
I see&ndash;I was hoping that widgets within the same plugin could share some sort of settings. I like your solution for making the _cycling_ through choices more intuitive! @amitabhverma

**Comment by amitabhverma** [comment]
@gschlafly @rudolfoldenbourg 
I've implemented the following with the latest /NN branch. The tabs on the side seem to save the vertical real-estate. Also, went for the single clickable cycling button for now.. maybe we can have that in a new WIP issue.

![image](https://user-images.githubusercontent.com/2894099/215820688-671bc0ce-9de9-47d7-9e82-f1e005b1153c.png)

**Comment by rudolfoldenbourg** [comment]
@gschlafly @amitabhverma 
Excellent, I like the vertical tabs on the left that are common to both processing modes. For the buttons Calibrate, Rectify, Deconvolve for LFAnalyze processing, and Deconvolve for Neural Net processing, I suggest to include them and the Stop button in the tab "Parameters" and call that tab "Processing".

**Comment by amitabhverma** [comment]
> @gschlafly @amitabhverma Excellent, I like the vertical tabs on the left that are common to both processing modes. For the buttons Calibrate, Rectify, Deconvolve for LFAnalyze processing, and Deconvolve for Neural Net processing, I suggest to include them and the Stop button in the tab "Parameters" and call that tab "Processing".

Implemented in latest /NN branch (https://github.com/PolarizedLightFieldMicroscopy/napari-LF/commit/6fecb290d34c9aed2409b350eea99d619be5d356)

![image](https://user-images.githubusercontent.com/2894099/215918896-24ebc2cf-88b5-49ae-aaa8-68d18b9ecd7b.png)
