### ISSUE TITLE
NN training jupyter notebook inconsistent volume shape

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/napari-LF#26]
#### Description
Unable to run the entire NN training jupyter notebook file on the Windows Workstation.

#### Files
- src\napari_lf\lfa\main_train_neural_net.ipynb
- src\napari_lf\lfa\neural_nets\LFMNet.py
- src\napari_lf\lfa\neural_nets\LFNeuralNetworkProto.py

#### To Reproduce
In the branch `NeuralNets_integration2`, run the script `main_train_neural_net.ipynb` up to and including section _5.2 Train the network_ and _6. Reconstruct a volume with the trained network_.

#### Error messages
Initial error log: [2023-01-20 error log.txt](https://github.com/PolarizedLightFieldMicroscopy/napari-LF/files/10484095/2023-01-20.error.log.txt)

After 88de9eeaec2224aa5fcc6beabbedfe5e7431b724 where the jupyter notebook was updated: Network gets trained! However, there are several warning messages on step 5.2, and step 6 produced the following error message: 
> RuntimeError: shape '[1, 1, 1287, 1287]' is invalid for input of size 2405601

**Comment by pvjosue** [comment]
Thanks for the info :) 
Fixed in commit: https://github.com/PolarizedLightFieldMicroscopy/napari-LF/commit/9ac6afafd2739bbed8130556868a380e06d45f9c
Input padding was performed at image loading time.
So this reshape failed as it was expecting an un-padded input image.
