### ISSUE TITLE
Include intensity pattern on outer slices of PSF

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/napari-LF#27]
#### Description
Only the middle slice of the extracted light field point spread function includes an intensity pattern. For example, see [psf_stack-SS4.tif](https://github.com/PolarizedLightFieldMicroscopy/napari-LF-docs-samples/blob/main/GUVSimul1/psf_stack-SS4.tif).

From @rudolfoldenbourg:

> When I use the notebook LF_forward_projector_simple.ipynb to extract the light field point spread function psf_stack-SS4.tif, this stack has indeed 104 slices which are all zero except for the 53rd slice that shows an intensity pattern behind the central lenslet. In addition, this pattern is asymmetric and not as expected for the central location of the point source behind the central lenslet. Curiously, when generating a calibration file with super sample = 3, this pattern is symmetric and as expected from wave optics simulations. However, regardless of the super sample setting, only the middle slice shows an intensity pattern, with all other slices zero. The corresponding psf stacks are named psf_stack-SS3.tif, psf_stack-SS4.tif, and psf_stack-SS5.tif.

#### Files
- src\napari_lf\lfa\LF_forward_projector_simple.ipynb

Images within the directory [napari-LF-docs-samples/GUVSimul1](https://github.com/PolarizedLightFieldMicroscopy/napari-LF-docs-samples/tree/main/GUVSimul1):
- Radiometry_GUVSimul1.tif
- output_stack-104.tif
- psf_stack-SS3.tif
- psf_stack-SS4.tif
- psf_stack-SS5.tif

#### To Reproduce
1. Generate a calibration lfc file with the LF image Radiometry_GUVSimul1.tif, 104 slices of 0.43µm apart, and a superssampling of 4.
2. Deconvolve using the RL iterative method to produce output_stack-104.tif.
3. Use LF_forward_projector_simple.ipynb to extract the light field point spread function psf_stack-SS4.tif.
4. Repeats Steps 1-3 with a super sample setting of 3 and 4 to extract psf_stack-SS3.tif and psf_stack-SS5.tif, respectively.

**Comment by pvjosue** [comment]
Let's see:
- Asymmetric PSF (not centered): This is expected for even SS (2,4,6,...), as there isn't a voxel that aligns with the center pixel of the central micro-lens. This is only possible for odd SS (1,3,5,7...)
- Only central depth PSF extracted: There's an option to select which depths to extract the PSF from in the Extract PSF cell:
```python
# Extract psf of coords relative to the center of the image
coord_x,coord_y = 1,1
# all the depths?
depths_to_extract = list(range(db.nz))
# or just some of them?
depths_to_extract = [db.nz//2]
```
by commenting `depths_to_extract = [db.nz//2]`, you'll get the expected behavior. 
![image](https://user-images.githubusercontent.com/1091910/214304470-5b802ef1-d6b8-4321-a704-48ae4b274d42.png)

**Comment by pvjosue** [comment]
Commented the line and ready to run in:
https://github.com/PolarizedLightFieldMicroscopy/napari-LF/commit/81f60821b0ab7160b39e69e146fc69c78a1a5a26
