### ISSUE TITLE
Animation for Presets and Comments fields is glitchy

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/napari-LF#30]
#### Description
The CollapsibleBox method works great for minimizing the space that the _Presets_ and _Comments_ fields consume within the widget. However, the animation is glitchy, as shown in the screen recording below.

![napari-LF collapsible presets](https://user-images.githubusercontent.com/23206511/215187334-3da9455b-8d01-40d1-b75e-48297c5f2e6e.gif)

#### Files
https://github.com/PolarizedLightFieldMicroscopy/napari-LF/blob/1cc187856aa351e8041b799eb10574338decd67d/src/napari_lf/_widgetLF_gui.py#L1172
https://github.com/PolarizedLightFieldMicroscopy/napari-LF/blob/1cc187856aa351e8041b799eb10574338decd67d/src/napari_lf/_widgetLF_gui.py#L1767-L1837

#### Solution ideas
- Make the nearby regions of fixed height instead of expandable height.
- Omit the animation effect by using a method other than the CollapsibleBox class, and have the surrounding fields move instantaneously.
- The [napari-assistant](https://www.napari-hub.org/plugins/napari-assistant) plugin may similarly being using a dropdown area method for their info boxes. I observed what appeared to be an attempted animation when I hovered over the ? in the top right corner and some of the large buttons, as shown in the video below. So this glitchiness may be an issue with napari in general. @haesleinhuepf may also have some ideas on how to fix this glitchiness.

https://user-images.githubusercontent.com/23206511/215195478-71a3448d-79fe-4784-92ef-2a98cab2eb4a.mp4

**Comment by amitabhverma** [comment]
That jitter looks so much better on your end, here's mine.. will look into your suggestion.

[ice_video_20230127-161442.webm](https://user-images.githubusercontent.com/2894099/215202020-7a198c5d-755b-4560-8343-54e7ba394661.webm)

**Comment by haesleinhuepf** [comment]
Hi all,

I presume it's a qt-issue or a napari issue. To know which of the two, I recommend reaching out to the napari-core devs to ask them about their opinion. They have weekly open community meetings, the perfect place to show stuff and ask for support:

https://napari.org/stable/community/meeting_schedule.html

I hope that helps. 🌞

Best,
Robert

**Comment by gschlafly** [comment]
Thanks!! @haesleinhuepf

**Comment by amitabhverma** [comment]
@gschlafly with the latest GUI changes, this seems more acceptable now.
[ice_video_20230131-201422.webm](https://user-images.githubusercontent.com/2894099/215921143-97339645-ca83-4f8c-be82-0c6f9ea49e10.webm)
