### ISSUE TITLE
Neural Net dependencies

### ISSUE THREAD

**Issue by gschlafly** [PolarizedLightFieldMicroscopy/napari-LF#32]
The _Neural Net_ component requires an additional set of packages to be installed. These should be included in the `setup.cfg` file.
https://github.com/PolarizedLightFieldMicroscopy/napari-LF/blob/4dd5174a137aab6b93c5f6bb32ce750f737d1136/setup.cfg#L39-L44
Additionally versions of the set of packages that get installed can be created. For example, to add a development version of the plugin, the following can be added to `setup.cfg`:
> [options.extras_require]
dev =
    flake8
    pytest>=5.0.0
    pytest-cov
    requests>=2.22.0
    wget>=3.2

A version could be created for just the _LF Analyze_ components, in case the _Neural Net_ components are not desired and the installation dependencies cause issues.

**Comment by amitabhverma** [comment]
And these as well:

```
conda install pytorch
conda install -c conda-forge pytorch-lightning
conda install -c pytorch torchvision
```

The above seemed to work before with my old .14 napari install. 
I had to install the above libs again using pip for some reason to get NN working in .17

```
pip install torch (it's 'torch' via pip)
pip install pytorch_lightning
pip install torchvision
```

**Comment by gschlafly** [comment]
Done in a94b37b98581cab8cbc0d3c9145db36e2f7f17d1, could still use machine-dependent installation instructions though.
